### ISSUE TITLE
Segmentation fault when starting on MacBook Pro M1 laptops

### ISSUE THREAD

**Issue by whummer** [etspaceman/kinesis-mock#128]
Some of our users in LocalStack have been facing Kinesis startup issues - especially on MacBook Pro M1 laptops, caused by this error during startup:
```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

Not entirely sure what would be the best way to debug this, as I currently don't have access to a M1 machine. One option would be to catch this error on LocalStack side, and then fall back to the legacy Kinesis provider (kinesalite), but ideally it would be great to see the root cause of this issue fixed properly. Otherwise, we run the risk of diverging too much with the different implementations we're using in LocalStack. 

Please let us know if there's anything we can help out with. Thanks for your help!

**Comment by etspaceman** [comment]
The binary for MacOS is built for AMD64 and not ARM, so that's the issue I'dthink. We'd want that to fall back to the jar file for these systems. I thought I had logic in localstack to detect that but it must not be working for these Macs.

**Comment by etspaceman** [comment]
I'll be submitting a PR later today that should help this. Unfortunately it'll be hard to test since neither GH Actions or CircleCI supports M1 processors. But we should be able to add a condition to the install script that detects ARM and falls back to the jar. 

Azul provides ARM jdk downloads on their website so users should be able to leverage a jar fine in this scenario.

**Comment by etspaceman** [comment]
See https://github.com/localstack/localstack/pull/4191, @whummer
